# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='rarity',
        ),
        migrations.AddField(
            model_name='cards',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cards',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
        migrations.AddField(
            model_name='cards',
            name='title',
            field=models.CharField(default='Card', max_length=255),
        ),
    ]
