# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 03:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160512_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='cards',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 13, 3, 11, 7, 985382, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
