# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20160513_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
