# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20160513_0318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('created', 'status')},
        ),
    ]
